#' Calculate the fdr hit rates for every sample in the data.
#'
#' To be honest, I am not yet sure how this is different from
#' assess_fdr_byrun(), so until I take some time to truly familiarize myself
#' with it, I will just put the docstring from that here.
#' This function calculates some metrics which describe how often each sample
#' passes the given m score thresholds.  Optionally it may also plot some of
#' these statistics.
#'
#' @param data  Data structure generated by sample_annotation()
#' @param FFT I have read the code for this function a few times now and I still
#'   do not know what this refers to.  I am going to say 'fast fourier
#'   transform', which is obviously not true.  I can say that it is a factor
#'   which is used to change the fdr_cube data, which is very much not the same
#'   thing as an answer.
#' @param  n_range  I am also not certain what this is, nor why 20 is the
#'   optimal default value, but I think the idea is to set up a series of mscore
#'   thresholds.
#' @param output  Send the result of this to a pdf/csv or the R console?
#' @param plot  Make some pretty bar plots of the results?
#' @param filename  Where to send the pdf/csv report (it seems to me this should
#'   be folded into the output parameter).
#' @export
assess_fdr_overall <-function(data, FFT=1, n_range=20, output="pdf_csv",
                              plot=TRUE, filename="FDR_report_overall") {
  mscore_levels <- 10 ^ - seq(n_range)
  ## create vectors to store count results
  target_assays <- NULL
  decoy_assays <- NULL
  target_peptides <- NULL
  decoy_peptides <- NULL
  target_proteins <- NULL
  decoy_proteins <- NULL

  # loop over IDs with different m_score thresholds counting targets & decoys
  for (i in seq_len(length(mscore_levels))) {
    target_assays[i] <- length(unique(data[data[["decoy"]] == FALSE &
                                           data[["m_score"]] <= mscore_levels[i],
                                           c("transition_group_id")]))
    decoy_assays[i] <- length(unique(data[data[["decoy"]] == TRUE &
                                          data[["m_score"]] <= mscore_levels[i],
                                          c("transition_group_id")]))
    target_peptides[i] <- length(unique(data[data[["decoy"]] == FALSE &
                                             data[["m_score"]] <= mscore_levels[i],
                                             c("fullpeptidename")]))
    decoy_peptides[i] <- length(unique(data[data[["decoy"]] == TRUE &
                                            data[["m_score"]] <= mscore_levels[i],
                                            c("fullpeptidename")]))
    target_proteins[i] <- length(unique(data[data[["decoy"]] == FALSE &
                                             data[["m_score"]] <= mscore_levels[i],
                                             c("proteinname")]))
    decoy_proteins[i] <- length(unique(data[data[["decoy"]] == TRUE &
                                            data[["m_score"]] <= mscore_levels[i],
                                            c("proteinname")]))
  }

  # calculate false target fraction at cutoff (FDR) by decoy fraction * FFT
  assay_fdr <- (decoy_assays / target_assays) * FFT
  peptide_fdr <- (decoy_peptides / target_peptides) * FFT
  protein_fdr <- (decoy_proteins / target_proteins) * FFT
  # calculate estimated number of true identifications among the target hits
  true_target_assays <- target_assays - (decoy_assays * FFT)
  true_target_peptides <- target_peptides - (decoy_peptides * FFT)
  true_target_proteins <- target_proteins - (decoy_proteins * FFT)

  fdr_table <- structure(list(
    "mscore_cutoff" = mscore_levels,
    "target_assays" = target_assays,
    "decoy_assays" = decoy_assays,
    "assay_fdr" = assay_fdr,
    "true_target_assays" = true_target_assays,
    "target_peptides" = target_peptides,
    "decoy_peptides" = decoy_peptides,
    "peptide_fdr" = peptide_fdr,
    "true_target_peptides" = true_target_peptides,
    "target_proteins" = target_proteins,
    "decoy_proteins" = decoy_proteins,
    "protein_fdr" = protein_fdr,
    "true_target_proteins" = true_target_proteins),
    class="fdr_table")

  if (isTRUE(plot)) {
    plotret <- plot_fdr_table(fdr_table, filename=filename, output=output)
  }

  if (output == "Rconsole") {
    return(fdr_table)
  }

  if (output == "pdf_csv") {
    fdr_table_csv <- cbind(mscore_levels, target_assays, decoy_assays,
                           assay_fdr, true_target_assays, target_peptides,
                           decoy_peptides, peptide_fdr, true_target_peptides,
                           target_proteins, decoy_proteins, protein_fdr, true_target_proteins)
    write.csv(fdr_table_csv, file=paste(filename, "table.csv", sep="_"), row.names=TRUE)
    message(paste0(filename, "_table.csv written to working folder"))
  }
  return(fdr_table)
}
